services:
  - type: web
    name: cyber-sentinel
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/virustotal_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    buildpacks:
      - url: heroku/python
      - url: https://github.com/heroku/heroku-buildpack-apt 